# Generated by Django 6.0.1 on 2026-01-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mealfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
