# Generated by Django 6.0.1 on 2026-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_meal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='culture_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='has_alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='has_blood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='has_pork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='price_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='culture_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
