# Generated by Django 6.0.1 on 2026-02-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_meal_culture_tags_meal_has_alcohol_meal_has_blood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_meal_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
