# Generated by Django 6.0.1 on 2026-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_preferred_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_goal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
