from django.core.management.base import BaseCommand
from api.models import Meal


class Command(BaseCommand):
    help = 'Seed initial meals'

    def handle(self, *args, **kwargs):
        meals = [
            {
                "name": "Chicken Adobo",
                "description": "Classic Filipino chicken adobo with soy sauce and vinegar",
                "calories": 450,
                "protein": 35,
                "carbs": 18,
                "fats": 24,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,sulfite,chicken,garlic,vinegar",
                "medication_warnings": "none",
            },
            {
                "name": "Sinigang na Isda",
                "description": "Tamarind fish soup with kangkong and radish",
                "calories": 320,
                "protein": 32,
                "carbs": 14,
                "fats": 10,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,tomato,radish,kangkong,tamarind",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Monggo with Malunggay",
                "description": "Sauteed mung bean stew with malunggay leaves",
                "calories": 330,
                "protein": 18,
                "carbs": 42,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "mung bean,malunggay,garlic,onion",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Tortang Talong",
                "description": "Eggplant omelette with garlic and onion",
                "calories": 280,
                "protein": 12,
                "carbs": 16,
                "fats": 16,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1e/EGGPLANT_TORTA.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "egg,eggplant,garlic,onion",
                "medication_warnings": "none",
            },
            {
                "name": "Tinolang Manok",
                "description": "Ginger chicken soup with papaya and chili leaves",
                "calories": 360,
                "protein": 34,
                "carbs": 12,
                "fats": 16,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrNMjYWrOBTPB3XACVJh_NT_XWLNwqpurZKA&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "chicken,papaya,ginger",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Pork Menudo",
                "description": "Tomato-based pork stew with potatoes and carrots",
                "calories": 520,
                "protein": 28,
                "carbs": 24,
                "fats": 32,
                "is_vegetarian": False,
                "is_halal": False,
                "image_url": "https://assets.unileversolutions.com/recipes-v2/214409.png",
                "has_pork": True,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "pork,tomato,liver,potato",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Pinakbet",
                "description": "Mixed vegetable dish with bagoong",
                "calories": 290,
                "protein": 10,
                "carbs": 34,
                "fats": 12,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsOY66nTSznrPYODwJ16npD_0TigopukOcWA&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,shellfish,bagoong,eggplant,bitter melon,squash,okra",
                "medication_warnings": "warfarin,maoi",
            },
            {
                "name": "Paksiw na Bangus",
                "description": "Milkfish simmered in vinegar with garlic",
                "calories": 340,
                "protein": 31,
                "carbs": 6,
                "fats": 20,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://kitchenomics.com/media/catalog/product/p/i/pina-paksiw-na-bangus_1.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,sulfite,milkfish,vinegar,garlic",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Laing",
                "description": "Taro leaves stewed in coconut milk",
                "calories": 310,
                "protein": 7,
                "carbs": 18,
                "fats": 24,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Laing%2C_Bicolano_dish.jpg/1280px-Laing%2C_Bicolano_dish.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "coconut,shellfish,taro,shrimp",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Lumpiang Gulay",
                "description": "Filipino vegetable spring rolls",
                "calories": 260,
                "protein": 9,
                "carbs": 30,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2019/04/lumpianggulayrecipe-1.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "gluten,soy,cabbage,carrot,wrapper",
                "medication_warnings": "none",
            },
            {
                "name": "Pandesal with Peanut Butter",
                "description": "Whole wheat pandesal served with peanut butter",
                "calories": 300,
                "protein": 11,
                "carbs": 42,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://media.karousell.com/media/photos/products/2024/8/12/traditional_homemade_peanut_bu_1723488442_e24e6dd8_progressive.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "gluten,peanut,wheat,bread",
                "medication_warnings": "levothyroxine",
            },
            {
                "name": "Saba Banana Cue",
                "description": "Caramelized saba bananas on skewers",
                "calories": 280,
                "protein": 2,
                "carbs": 58,
                "fats": 4,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTLIpAqo7oG3cESwGlvGdLDndjIi_laz04lw&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "banana",
                "medication_warnings": "metformin,insulin",
            },
            {
                "name": "Arroz Caldo",
                "description": "Filipino rice porridge with chicken and ginger",
                "calories": 340,
                "protein": 20,
                "carbs": 40,
                "fats": 10,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2017/05/Chicken-Arroz-Caldo-2.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "chicken,ginger,rice",
                "medication_warnings": "none",
            },
            {
                "name": "Lugaw with Egg",
                "description": "Simple Filipino congee topped with boiled egg",
                "calories": 300,
                "protein": 12,
                "carbs": 42,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2022/12/lugaw-with-egg-640.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "egg,rice",
                "medication_warnings": "none",
            },
            {
                "name": "Champorado with Milk",
                "description": "Chocolate rice porridge with evaporated milk",
                "calories": 360,
                "protein": 8,
                "carbs": 64,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiqVmMtqe7IOULe9GRltv5b7LOZbbkUgV8Dg&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "milk,cocoa",
                "medication_warnings": "metformin,insulin",
            },
            {
                "name": "Bicol Express",
                "description": "Spicy pork stew in coconut milk",
                "calories": 560,
                "protein": 24,
                "carbs": 10,
                "fats": 46,
                "is_vegetarian": False,
                "is_halal": False,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2021/04/Bicol-Express-1.jpg",
                "has_pork": True,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "pork,coconut,shellfish,shrimp,chili",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Ginataang Kalabasa at Sitaw",
                "description": "Squash and string beans in coconut milk",
                "calories": 280,
                "protein": 8,
                "carbs": 22,
                "fats": 16,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.deliveryhero.io/image/foodpanda/recipes/ginataang-kalabasa-recipe-1.png",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "coconut,shellfish,squash,string bean,shrimp",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Daing na Bangus",
                "description": "Marinated and fried milkfish",
                "calories": 390,
                "protein": 33,
                "carbs": 4,
                "fats": 26,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://i0.wp.com/www.angsarap.net/wp-content/uploads/2020/01/Daing-na-Bangus-Wide.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,sulfite,milkfish,vinegar",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Inihaw na Tilapia",
                "description": "Char-grilled tilapia with calamansi and soy dip",
                "calories": 350,
                "protein": 34,
                "carbs": 6,
                "fats": 20,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://theasfoodandplaces.wordpress.com/wp-content/uploads/2018/10/5329073849_89896f3cb8.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,soy,tilapia,calamansi",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Pancit Bihon",
                "description": "Stir-fried rice noodles with vegetables and chicken",
                "calories": 420,
                "protein": 18,
                "carbs": 58,
                "fats": 12,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://i0.wp.com/victoriarosefoodie.com/wp-content/uploads/2025/02/FIL08067-scaled.jpg?fit=2560%2C1707&ssl=1",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,chicken,rice noodle,cabbage,carrot",
                "medication_warnings": "none",
            },
            {
                "name": "Sotanghon Soup",
                "description": "Glass noodle soup with chicken and vegetables",
                "calories": 330,
                "protein": 17,
                "carbs": 44,
                "fats": 9,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2010/10/Chicken-Sotanghon-Soup-500x485.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,chicken,glass noodle,carrot,cabbage",
                "medication_warnings": "none",
            },
            {
                "name": "Ukoy",
                "description": "Crispy shrimp and vegetable fritters",
                "calories": 370,
                "protein": 16,
                "carbs": 32,
                "fats": 18,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://www.seriouseats.com/thmb/s_V04vS3qK_xcJTQLsHAdkmaMVI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210617-ukoy-vicky-wasik-seriouseats-seriouseats-17-3aecd8efbaa54fc59276cd79b8acf72e.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "shellfish,egg,gluten,shrimp,bean sprout,flour",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Tokwa't Gulay",
                "description": "Sauteed tofu with mixed vegetables",
                "calories": 290,
                "protein": 16,
                "carbs": 18,
                "fats": 14,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2021/09/chilitofu.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,tofu,carrot,cabbage",
                "medication_warnings": "levothyroxine",
            },
            {
                "name": "Adobong Kangkong",
                "description": "Water spinach cooked adobo-style with soy and vinegar",
                "calories": 170,
                "protein": 5,
                "carbs": 14,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://www.sentro1771.com/wp-content/uploads/2022/11/Adobong-Kangkong.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,sulfite,kangkong,vinegar",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Ampalaya with Egg",
                "description": "Sauteed bitter melon with egg, onion, and tomato",
                "calories": 190,
                "protein": 9,
                "carbs": 12,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/58/Ampalaya.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "egg,bitter melon,tomato,onion",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginataang Gulay",
                "description": "Mixed local vegetables simmered in coconut milk",
                "calories": 260,
                "protein": 7,
                "carbs": 24,
                "fats": 16,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/60/Ginataang_gulay.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "coconut,squash,string bean,eggplant,okra",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Dinengdeng",
                "description": "Ilocano vegetable soup with grilled fish and bagoong broth",
                "calories": 230,
                "protein": 13,
                "carbs": 18,
                "fats": 10,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/9/93/Dinengdeng.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,ilocano,gulay",
                "allergen_tags": "fish,bagoong,okra,eggplant,bitter melon,string bean",
                "medication_warnings": "warfarin,allopurinol",
            },
            {
                "name": "Bulanglang na Gulay",
                "description": "Light vegetable soup with squash, okra, and string beans",
                "calories": 150,
                "protein": 4,
                "carbs": 20,
                "fats": 5,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Bulanglang.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "squash,okra,string bean,eggplant",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Utan Bisaya",
                "description": "Visayan vegetable soup with squash, malunggay, and corn",
                "calories": 180,
                "protein": 5,
                "carbs": 24,
                "fats": 6,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/a/a4/Utan_bisaya.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,visayan,gulay",
                "allergen_tags": "malunggay,squash,corn,string bean",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginataang Langka",
                "description": "Young jackfruit cooked in coconut milk with aromatics",
                "calories": 240,
                "protein": 5,
                "carbs": 22,
                "fats": 15,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Ginataang_Langka.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,bicolano,gulay",
                "allergen_tags": "coconut,jackfruit,chili",
                "medication_warnings": "none",
            },
            {
                "name": "Ensaladang Talong",
                "description": "Roasted eggplant salad with tomato and onion",
                "calories": 120,
                "protein": 3,
                "carbs": 10,
                "fats": 7,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/4/47/Ensaladang_talong.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "eggplant,tomato,onion",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Sayote",
                "description": "Sauteed chayote with garlic, onion, and tomato",
                "calories": 140,
                "protein": 3,
                "carbs": 16,
                "fats": 7,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Sayote.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "chayote,tomato,onion,garlic",
                "medication_warnings": "none",
            },
            {
                "name": "Ginisang Repolyo at Carrots",
                "description": "Sauteed cabbage and carrots, a simple Filipino vegetable side",
                "calories": 150,
                "protein": 4,
                "carbs": 14,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/14/Cabbage.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "cabbage,carrot,onion,garlic",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Upo",
                "description": "Bottle gourd sauteed with garlic and tomatoes",
                "calories": 135,
                "protein": 3,
                "carbs": 13,
                "fats": 7,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Bottle_gourd.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "bottle gourd,tomato,onion,garlic",
                "medication_warnings": "none",
            },
            {
                "name": "Ginisang Pechay with Tofu",
                "description": "Sauteed bok choy with tofu in a light savory sauce",
                "calories": 180,
                "protein": 11,
                "carbs": 10,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Bok_choy.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "soy,tofu,pechay,garlic,onion",
                "medication_warnings": "warfarin,levothyroxine",
            },
            {
                "name": "Munggo Guisado with Kalabasa",
                "description": "Sauteed mung bean stew with squash and leafy greens",
                "calories": 310,
                "protein": 16,
                "carbs": 38,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Munggo.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "mung bean,squash,malunggay,garlic,onion",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Tortang Dulong",
                "description": "Filipino silverfish omelette, commonly served for breakfast",
                "calories": 250,
                "protein": 19,
                "carbs": 6,
                "fats": 16,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5d/Torta.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,egg,silverfish,onion",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Rellenong Talong",
                "description": "Stuffed eggplant with egg and vegetables",
                "calories": 230,
                "protein": 10,
                "carbs": 14,
                "fats": 13,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Eggplant.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "egg,eggplant,carrot,onion",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Chicken Inasal",
                "description": "Grilled chicken marinated with calamansi, vinegar, and annatto",
                "calories": 410,
                "protein": 36,
                "carbs": 8,
                "fats": 24,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/17/Chicken_inasal.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy,visayan",
                "allergen_tags": "chicken,sulfite,vinegar,calamansi",
                "medication_warnings": "none",
            },
            {
                "name": "Pesang Isda",
                "description": "Poached fish soup with pechay, ginger, and potatoes",
                "calories": 290,
                "protein": 27,
                "carbs": 14,
                "fats": 12,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Fish_soup.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,pechay,ginger,potato",
                "medication_warnings": "allopurinol,warfarin",
            },
            {
                "name": "Adobong Sitaw",
                "description": "String beans cooked adobo-style with garlic and soy sauce",
                "calories": 165,
                "protein": 5,
                "carbs": 16,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/32/String_beans.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "soy,sulfite,string bean,vinegar,garlic",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Patola with Misua",
                "description": "Sponge gourd soup with misua noodles and light aromatics",
                "calories": 170,
                "protein": 4,
                "carbs": 22,
                "fats": 6,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/0/0d/Patola.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy,gulay",
                "allergen_tags": "gluten,wheat,misua,sponge gourd,garlic,onion",
                "medication_warnings": "none",
            },
            {
                "name": "Pritong Galunggong",
                "description": "Pan-fried round scad, a common Filipino home-style dish",
                "calories": 330,
                "protein": 30,
                "carbs": 2,
                "fats": 22,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/b/b2/Galunggong.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,round scad",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Tinolang Isda",
                "description": "Fish soup with ginger, tomato, and leafy vegetables",
                "calories": 260,
                "protein": 26,
                "carbs": 8,
                "fats": 12,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Fish_stew.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,ginger,tomato,malunggay",
                "medication_warnings": "allopurinol,warfarin",
            },
            {
                "name": "Sinigang na Hipon",
                "description": "Tamarind shrimp soup with kangkong, radish, and okra",
                "calories": 280,
                "protein": 24,
                "carbs": 14,
                "fats": 12,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/3/34/Sinigang_na_hipon.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "shellfish,shrimp,tamarind,kangkong,okra,radish",
                "medication_warnings": "allopurinol,warfarin",
            },
        ]

        created_count = 0
        for meal in meals:
            _, created = Meal.objects.update_or_create(
                name=meal["name"],
                defaults=meal,
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Philippine meals seeded successfully. Added {created_count} new meals and synced existing meals by name."
            )
        )
