from django.core.management.base import BaseCommand
from api.models import Meal


class Command(BaseCommand):
    help = 'Seed initial meals'

    def handle(self, *args, **kwargs):
        meals = [
            {
                "name": "Chicken Adobo",
                "description": "Classic Filipino chicken adobo with soy sauce and vinegar",
                "calories": 450,
                "protein": 35,
                "carbs": 18,
                "fats": 24,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,sulfite",
                "medication_warnings": "none",
            },
            {
                "name": "Sinigang na Isda",
                "description": "Tamarind fish soup with kangkong and radish",
                "calories": 320,
                "protein": 32,
                "carbs": 14,
                "fats": 10,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Ginisang Monggo with Malunggay",
                "description": "Sauteed mung bean stew with malunggay leaves",
                "calories": 330,
                "protein": 18,
                "carbs": 42,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.unsplash.com/photo-1547592166-23ac45744acd",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "none",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Tortang Talong",
                "description": "Eggplant omelette with garlic and onion",
                "calories": 280,
                "protein": 12,
                "carbs": 16,
                "fats": 16,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/1/1e/EGGPLANT_TORTA.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "egg",
                "medication_warnings": "none",
            },
            {
                "name": "Tinolang Manok",
                "description": "Ginger chicken soup with papaya and chili leaves",
                "calories": 360,
                "protein": 34,
                "carbs": 12,
                "fats": 16,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrNMjYWrOBTPB3XACVJh_NT_XWLNwqpurZKA&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "none",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Pork Menudo",
                "description": "Tomato-based pork stew with potatoes and carrots",
                "calories": 520,
                "protein": 28,
                "carbs": 24,
                "fats": 32,
                "is_vegetarian": False,
                "is_halal": False,
                "image_url": "https://assets.unileversolutions.com/recipes-v2/214409.png",
                "has_pork": True,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "none",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Pinakbet",
                "description": "Mixed vegetable dish with bagoong",
                "calories": 290,
                "protein": 10,
                "carbs": 34,
                "fats": 12,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsOY66nTSznrPYODwJ16npD_0TigopukOcWA&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,shellfish",
                "medication_warnings": "warfarin,maoi",
            },
            {
                "name": "Paksiw na Bangus",
                "description": "Milkfish simmered in vinegar with garlic",
                "calories": 340,
                "protein": 31,
                "carbs": 6,
                "fats": 20,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://kitchenomics.com/media/catalog/product/p/i/pina-paksiw-na-bangus_1.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,sulfite",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Laing",
                "description": "Taro leaves stewed in coconut milk",
                "calories": 310,
                "protein": 7,
                "carbs": 18,
                "fats": 24,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Laing%2C_Bicolano_dish.jpg/1280px-Laing%2C_Bicolano_dish.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "coconut,shellfish",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Lumpiang Gulay",
                "description": "Filipino vegetable spring rolls",
                "calories": 260,
                "protein": 9,
                "carbs": 30,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2019/04/lumpianggulayrecipe-1.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "gluten,soy",
                "medication_warnings": "none",
            },
            {
                "name": "Pandesal with Peanut Butter",
                "description": "Whole wheat pandesal served with peanut butter",
                "calories": 300,
                "protein": 11,
                "carbs": 42,
                "fats": 10,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://media.karousell.com/media/photos/products/2024/8/12/traditional_homemade_peanut_bu_1723488442_e24e6dd8_progressive.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "gluten,peanut",
                "medication_warnings": "levothyroxine",
            },
            {
                "name": "Saba Banana Cue",
                "description": "Caramelized saba bananas on skewers",
                "calories": 280,
                "protein": 2,
                "carbs": 58,
                "fats": 4,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTLIpAqo7oG3cESwGlvGdLDndjIi_laz04lw&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "none",
                "medication_warnings": "metformin,insulin",
            },
            {
                "name": "Arroz Caldo",
                "description": "Filipino rice porridge with chicken and ginger",
                "calories": 340,
                "protein": 20,
                "carbs": 40,
                "fats": 10,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2017/05/Chicken-Arroz-Caldo-2.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "none",
                "medication_warnings": "none",
            },
            {
                "name": "Lugaw with Egg",
                "description": "Simple Filipino congee topped with boiled egg",
                "calories": 300,
                "protein": 12,
                "carbs": 42,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2022/12/lugaw-with-egg-640.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "egg",
                "medication_warnings": "none",
            },
            {
                "name": "Champorado with Milk",
                "description": "Chocolate rice porridge with evaporated milk",
                "calories": 360,
                "protein": 8,
                "carbs": 64,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiqVmMtqe7IOULe9GRltv5b7LOZbbkUgV8Dg&s",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "milk",
                "medication_warnings": "metformin,insulin",
            },
            {
                "name": "Bicol Express",
                "description": "Spicy pork stew in coconut milk",
                "calories": 560,
                "protein": 24,
                "carbs": 10,
                "fats": 46,
                "is_vegetarian": False,
                "is_halal": False,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2021/04/Bicol-Express-1.jpg",
                "has_pork": True,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "coconut,shellfish",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Ginataang Kalabasa at Sitaw",
                "description": "Squash and string beans in coconut milk",
                "calories": 280,
                "protein": 8,
                "carbs": 22,
                "fats": 16,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.deliveryhero.io/image/foodpanda/recipes/ginataang-kalabasa-recipe-1.png",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "coconut,shellfish",
                "medication_warnings": "warfarin",
            },
            {
                "name": "Daing na Bangus",
                "description": "Marinated and fried milkfish",
                "calories": 390,
                "protein": 33,
                "carbs": 4,
                "fats": 26,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://i0.wp.com/www.angsarap.net/wp-content/uploads/2020/01/Daing-na-Bangus-Wide.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "breakfast",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,sulfite",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Inihaw na Tilapia",
                "description": "Char-grilled tilapia with calamansi and soy dip",
                "calories": 350,
                "protein": 34,
                "carbs": 6,
                "fats": 20,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://theasfoodandplaces.wordpress.com/wp-content/uploads/2018/10/5329073849_89896f3cb8.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "medium",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "fish,soy",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Pancit Bihon",
                "description": "Stir-fried rice noodles with vegetables and chicken",
                "calories": 420,
                "protein": 18,
                "carbs": 58,
                "fats": 12,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://i0.wp.com/victoriarosefoodie.com/wp-content/uploads/2025/02/FIL08067-scaled.jpg?fit=2560%2C1707&ssl=1",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy",
                "medication_warnings": "none",
            },
            {
                "name": "Sotanghon Soup",
                "description": "Glass noodle soup with chicken and vegetables",
                "calories": 330,
                "protein": 17,
                "carbs": 44,
                "fats": 9,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://panlasangpinoy.com/wp-content/uploads/2010/10/Chicken-Sotanghon-Soup-500x485.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "dinner",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy",
                "medication_warnings": "none",
            },
            {
                "name": "Ukoy",
                "description": "Crispy shrimp and vegetable fritters",
                "calories": 370,
                "protein": 16,
                "carbs": 32,
                "fats": 18,
                "is_vegetarian": False,
                "is_halal": True,
                "image_url": "https://www.seriouseats.com/thmb/s_V04vS3qK_xcJTQLsHAdkmaMVI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210617-ukoy-vicky-wasik-seriouseats-seriouseats-17-3aecd8efbaa54fc59276cd79b8acf72e.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "snack",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "shellfish,egg,gluten",
                "medication_warnings": "allopurinol",
            },
            {
                "name": "Tokwa't Gulay",
                "description": "Sauteed tofu with mixed vegetables",
                "calories": 290,
                "protein": 16,
                "carbs": 18,
                "fats": 14,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://images.yummy.ph/yummy/uploads/2021/09/chilitofu.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy",
                "medication_warnings": "levothyroxine",
            },
            {
                "name": "Adobong Kangkong",
                "description": "Water spinach cooked adobo-style with soy and vinegar",
                "calories": 170,
                "protein": 5,
                "carbs": 14,
                "fats": 8,
                "is_vegetarian": True,
                "is_halal": True,
                "image_url": "https://www.sentro1771.com/wp-content/uploads/2022/11/Adobong-Kangkong.jpg",
                "has_pork": False,
                "has_blood": False,
                "has_alcohol": False,
                "meal_time": "lunch",
                "price_level": "cheap",
                "culture_tags": "filipino,philippines,pinoy",
                "allergen_tags": "soy,sulfite",
                "medication_warnings": "warfarin",
            },
        ]

        created_count = 0
        for meal in meals:
            _, created = Meal.objects.get_or_create(
                name=meal["name"],
                defaults=meal,
            )
            if created:
                created_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Philippine meals seeded successfully. Added {created_count} new meals without modifying existing ones."
            )
        )
