release: python manage.py collectstatic --noinput && python manage.py migrate && python manage.py set_admin_password && python manage.py seed_meals
web: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
